{
    "questionsList"; [{
            "category": "Entertainment: Video Games",
            "questions": [
                {
                    "question": "When was Steam first released?",
                    "options": ["2003","2004","2011","2007"],
                    "answer": "2003",
                    "worth": 2
                }, 
                {
                    "question": "How many games in the Crash Bandicoot series were released on the original Playstation?",
                    "options": ["5","4","3", "6"],
                    "answer": "5",
                    "worth": 4
                },
                {
                    "question": "Which game did NOT get financed via Crowdfunding?",
                    "options": ["Enter the Gungeon","Town of Salem",
,"Undertale", "Tower Unite"],
                    "answer": "Enter The Gungeon",
                    "worth": 5
                }, 
                {
                    "question": "Which of the following characters from the game Overwatch was revealed to be homosexual?",
                    "options": ["Tracer","Widowmaker","Sombra", "Symmetra"],
                    "answer": "Tracer",
                    "worth": 3
                }, 
                {
                    "question": "In which series of games do you collect souls to empower you and buy weaponry and armor with?",
                    "options": ["The Legend of Zelda","Monster Hunter","Final Fantasy", "Souls "],
                    "answer": "Souls",
                    "worth": 1
                }, 
                {
                    "question": "What was the world's first video game?",
                    "options": ["Space Travel","Tennis for Two","Spacewar", "Pong"],
                    "answer": "Tennis for Two",
                    "worth": 1
                }, 
                {
                    "question": "In Super Mario Bros, the clouds and bushes have the same artwork and are just different colors.",
                    "options": ["True", "False"],
                    "answer": "True",
                    "worth": 3
                }, 
                {
                    "question": "Who was the first female protagonist in a video game?",
                    "options": ["Alis Landale","Chell","Samus Aran", "Lara Croft"],
                    "answer": "5",
                    "worth": 2
                },
                {
                    "question": "In the game Dark Souls, what is the name of the region you're in for the majority of the game?",
                    "options": ["Catarina","Drangleic","Oolacile", "Lordran"],
                    "answer": "Lordran",
                    "worth": 5
                },
                {
                    "question": "Minecraft can be played with a virtual reality headset.",
                    "options": ["5","4","3", "6"],
                    "answer": "5",
                    "worth": 1
                },
                {
                    "question": "How many differently shaped Tetris pieces are there?",
                    "options": ["5","12","7", "8"],
                    "answer": "7",
                    "worth": 2
                },
                {
                    "question": "Who turns out to be the true victor in the Battle of Armageddon in Mortal Kombat?",
                    "options": ["Shang Tsung","Shang Tsung","Shao Kahn", "Liu Kang"],
                    "answer": "Shao Kahn",
                    "worth": 4
                },
                {
                    "question": "Which of the following was not developed by Bethesda?",
                    "options": ["Fallout: New Vegas","Fallout 3","The Elder Scrolls V: Skyrim", "Fallout 4"],
                    "answer": "Fallout: New Vegas",
                    "worth": 1
                },
                {
                    "question": "Which of the following is NOT one of the main characters in Grand Theft Auto V's story mode?",
                    "options": ["Michael de Santa","Tommy Vercetti","Franklin Clinton", "Trevor Phillips"],
                    "answer": "Tommy Vercetti",
                    "worth": 1
                },
                {
                    "question": "The game Battlefield 1 takes place during World War I",
                    "options": ["True", "False"],
                    "answer": "True",
                    "worth": 1
                },
                {
                    "question": "What is Pikachu's National Dex Number?",
                    "options": ["#001","#109","#031", "#025"],
                    "answer": "#025",
                    "worth": 3
                },
                {
                    "question": "Which popular First Person Shooter (FPS) franchise, got a Real Time Strategy (RTS) game developed based on its universe?",
                    "options": ["Halo","Battlefield","Call of Duty", "Borderlands"],
                    "answer": "Halo",
                    "worth": 3
                },
                {
                    "question": "Who created the digital distribution platform Steam?",
                    "options": ["Ubisoft","Pixeltail Games","Valve", "Electronic Arts"],
                    "answer": "Valve",
                    "worth": 2
                },
                {
                    "question": "In the video game, Half-life, what event started the Half-life universe as we know today?",
                    "options": ["The Xen Attack","World War 3","The Resonance Cascade", "The Black Mesa Nuke"],
                    "answer": "The Resonance Cascade",
                    "worth": 5
                },
                {
                    "question": "In which year was League of Legends released?",
                    "options": ["2010","2009","2001", "2003"],
                    "answer": "2009",
                    "worth": 3
                },
                

            ]}]}
